# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\zuzia_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PySide2 import QtCore, QtWidgets, QtGui
from PySide2.QtCore import QPropertyAnimation
from PySide2.QtGui import QColor, QPixmap
from PySide2.QtUiTools import loadUiType
from PySide2.QtWidgets import *


from ui_splash_screen import Ui_SplashScreen

COUNTER = 0


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1038, 718)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(36, 34, 37);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_header = QtWidgets.QFrame(self.centralwidget)
        self.main_header.setMaximumSize(QtCore.QSize(16777215, 70))
        self.main_header.setStyleSheet("background-color: rgb(155, 192, 52);")
        self.main_header.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.main_header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_header.setObjectName("main_header")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.main_header)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.title_bar_container = QtWidgets.QFrame(self.main_header)
        self.title_bar_container.setStyleSheet("background-color: rgb(155, 192, 52);")
        self.title_bar_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_bar_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_bar_container.setObjectName("title_bar_container")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.title_bar_container)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.left_menu_toggle = QtWidgets.QFrame(self.title_bar_container)
        self.left_menu_toggle.setMinimumSize(QtCore.QSize(75, 0))
        self.left_menu_toggle.setMaximumSize(QtCore.QSize(85, 16777215))
        self.left_menu_toggle.setStyleSheet("background-color: rgb(155, 192, 52);")
        self.left_menu_toggle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_menu_toggle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_menu_toggle.setObjectName("left_menu_toggle")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.left_menu_toggle)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.menu_btn = QtWidgets.QPushButton(self.left_menu_toggle)
        self.menu_btn.setMinimumSize(QtCore.QSize(85, 0))
        self.menu_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.menu_btn.setStyleSheet("QPushButton {\n"
                                    "    border-style: outset;\n"
                                    "    border-radius: 25px;\n"
                                    "    border-color: rgb(36, 34, 37);\n"
                                    "    padding: 4px;\n"
                                    "}\n"
                                    "QPushButton::pressed {\n"
                                    "    border-style: outset;\n"
                                    "    border-radius: 25px;\n"
                                    "    border-color: rgb(36, 34, 37);\n"
                                    "    padding: 4px;\n"
                                    "    background-color: rgb(36, 34, 37);\n"
                                    "}")
        self.menu_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/list.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_btn.setIcon(icon)
        self.menu_btn.setIconSize(QtCore.QSize(50, 50))
        self.menu_btn.setObjectName("menu_btn")
        self.horizontalLayout_4.addWidget(self.menu_btn)
        self.horizontalLayout_5.addWidget(self.left_menu_toggle)
        self.title_bar = QtWidgets.QFrame(self.title_bar_container)
        self.title_bar.setMaximumSize(QtCore.QSize(16777015, 70))
        self.title_bar.setStyleSheet("background-color: rgb(155, 192, 52);")
        self.title_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.title_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_bar.setObjectName("title_bar")
        self.horizontalLayout_5.addWidget(self.title_bar)
        self.horizontalLayout_3.addWidget(self.title_bar_container)
        self.top_right_btns = QtWidgets.QFrame(self.main_header)
        self.top_right_btns.setMaximumSize(QtCore.QSize(75, 16777215))
        self.top_right_btns.setStyleSheet("background-color: rgb(155, 192, 52);")
        self.top_right_btns.setFrameShape(QtWidgets.QFrame.HLine)
        self.top_right_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_right_btns.setObjectName("top_right_btns")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.top_right_btns)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.minimize_btn = QtWidgets.QPushButton(self.top_right_btns)
        self.minimize_btn.setStyleSheet("")
        self.minimize_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimize_btn.setIcon(icon1)
        self.minimize_btn.setIconSize(QtCore.QSize(24, 24))
        self.minimize_btn.setObjectName("minimize_btn")
        self.horizontalLayout_2.addWidget(self.minimize_btn)
        self.close_btn = QtWidgets.QPushButton(self.top_right_btns)
        self.close_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/error.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_btn.setIcon(icon2)
        self.close_btn.setIconSize(QtCore.QSize(24, 24))
        self.close_btn.setObjectName("close_btn")
        self.horizontalLayout_2.addWidget(self.close_btn, 0, QtCore.Qt.AlignRight | QtCore.Qt.AlignVCenter)
        self.horizontalLayout_3.addWidget(self.top_right_btns)
        self.verticalLayout.addWidget(self.main_header)
        self.main_body = QtWidgets.QFrame(self.centralwidget)
        self.main_body.setStyleSheet("background-color: rgb(36, 34, 37);")
        self.main_body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_body.setObjectName("main_body")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.main_body)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_side_menu = QtWidgets.QFrame(self.main_body)
        self.left_side_menu.setMinimumSize(QtCore.QSize(85, 0))
        self.left_side_menu.setMaximumSize(QtCore.QSize(85, 16777215))
        self.left_side_menu.setStyleSheet("background-color: rgb(155, 192, 52);")
        self.left_side_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.left_side_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_side_menu.setObjectName("left_side_menu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.left_side_menu)
        self.verticalLayout_2.setContentsMargins(7, 0, 7, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.profile_btn = QtWidgets.QPushButton(self.left_side_menu)
        self.profile_btn.setMinimumSize(QtCore.QSize(0, 75))
        font = QtGui.QFont()
        font.setFamily("Chiller")
        font.setPointSize(28)
        self.profile_btn.setFont(font)
        self.profile_btn.setStyleSheet("QPushButton {\n"
                                       "    background-image: url(:/icons/icons/buka.png);\n"
                                       "    background-repeat: none;\n"
                                       "    background-position: center left;\n"
                                       "    border-style: outset;\n"
                                       "    border-radius: 37px;\n"
                                       "    border-color: rgb(36, 34, 37);\n"
                                       "    padding-left: 100px;\n"
                                       "}\n"
                                       "QPushButton::pressed {\n"
                                       "    background-image: url(:/icons/icons/buka.png);\n"
                                       "    background-repeat: none;\n"
                                       "    background-position: center left;\n"
                                       "    border-style: outset;\n"
                                       "    border-radius: 37px;\n"
                                       "    border-color: rgb(36, 34, 37);\n"
                                       "    padding-left: 100px;\n"
                                       "    background-color: rgb(36, 34, 37);\n"
                                       "}")
        self.profile_btn.setIconSize(QtCore.QSize(50, 50))
        self.profile_btn.setObjectName("profile_btn")
        self.verticalLayout_2.addWidget(self.profile_btn)
        self.time_btn = QtWidgets.QPushButton(self.left_side_menu)
        self.time_btn.setMinimumSize(QtCore.QSize(0, 75))
        font = QtGui.QFont()
        font.setFamily("Chiller")
        font.setPointSize(28)
        self.time_btn.setFont(font)
        self.time_btn.setStyleSheet("QPushButton {\n"
                                    "    background-image: url(:/icons/icons/time.png);\n"
                                    "    background-repeat: none;\n"
                                    "    background-position: center left;\n"
                                    "    border-style: outset;\n"
                                    "    border-radius: 37px;\n"
                                    "    border-color: rgb(36, 34, 37);\n"
                                    "    padding-left: 100px;\n"
                                    "}\n"
                                    "QPushButton::pressed {\n"
                                    "    background-image: url(:/icons/icons/time.png);\n"
                                    "    background-repeat: none;\n"
                                    "    background-position: center left;\n"
                                    "    border-style: outset;\n"
                                    "    border-radius: 37px;\n"
                                    "    border-color: rgb(36, 34, 37);\n"
                                    "    padding-left: 100px;\n"
                                    "    background-color: rgb(36, 34, 37);\n"
                                    "}")
        self.time_btn.setIconSize(QtCore.QSize(50, 50))
        self.time_btn.setObjectName("time_btn")
        self.verticalLayout_2.addWidget(self.time_btn)
        self.notes_btn = QtWidgets.QPushButton(self.left_side_menu)
        self.notes_btn.setMinimumSize(QtCore.QSize(0, 75))
        font = QtGui.QFont()
        font.setFamily("Chiller")
        font.setPointSize(28)
        self.notes_btn.setFont(font)
        self.notes_btn.setStyleSheet("QPushButton {\n"
                                     "    background-image: url(:/icons/icons/notes.png);\n"
                                     "    background-repeat: none;\n"
                                     "    background-position: center left;\n"
                                     "    border-style: outset;\n"
                                     "    border-radius: 37px;\n"
                                     "    border-color: rgb(36, 34, 37);\n"
                                     "    padding-left: 100px;\n"
                                     "}\n"
                                     "QPushButton::pressed {\n"
                                     "    background-image: url(:/icons/icons/notes.png);\n"
                                     "    background-repeat: none;\n"
                                     "    background-position: center left;\n"
                                     "    border-style: outset;\n"
                                     "    border-radius: 37px;\n"
                                     "    border-color: rgb(36, 34, 37);\n"
                                     "    padding-left: 100px;\n"
                                     "    background-color: rgb(36, 34, 37);\n"
                                     "}")
        self.notes_btn.setIconSize(QtCore.QSize(50, 50))
        self.notes_btn.setObjectName("notes_btn")
        self.verticalLayout_2.addWidget(self.notes_btn)
        self.settings_btn = QtWidgets.QPushButton(self.left_side_menu)
        self.settings_btn.setMinimumSize(QtCore.QSize(0, 75))
        font = QtGui.QFont()
        font.setFamily("Chiller")
        font.setPointSize(28)
        self.settings_btn.setFont(font)
        self.settings_btn.setStyleSheet("QPushButton {\n"
                                        "    background-image: url(:/icons/icons/settings.png);\n"
                                        "    background-repeat: none;\n"
                                        "    background-position: center left;\n"
                                        "    border-style: outset;\n"
                                        "    border-radius: 37px;\n"
                                        "    border-color: rgb(36, 34, 37);\n"
                                        "    padding-left: 100px;\n"
                                        "}\n"
                                        "QPushButton::pressed {\n"
                                        "    background-image: url(:/icons/icons/settings.png);\n"
                                        "    background-repeat: none;\n"
                                        "    background-position: center left;\n"
                                        "    border-style: outset;\n"
                                        "    border-radius: 37px;\n"
                                        "    border-color: rgb(36, 34, 37);\n"
                                        "    padding-left: 100px;\n"
                                        "    background-color: rgb(36, 34, 37);\n"
                                        "}")
        self.settings_btn.setIconSize(QtCore.QSize(50, 50))
        self.settings_btn.setObjectName("settings_btn")
        self.verticalLayout_2.addWidget(self.settings_btn)
        self.horizontalLayout.addWidget(self.left_side_menu)
        self.right_side_menu = QtWidgets.QFrame(self.main_body)
        self.right_side_menu.setStyleSheet("background-color: rgb(36, 34, 37);")
        self.right_side_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.right_side_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_side_menu.setObjectName("right_side_menu")
        self.horizontalLayout.addWidget(self.right_side_menu)
        self.verticalLayout.addWidget(self.main_body)
        self.main_footer = QtWidgets.QFrame(self.centralwidget)
        self.main_footer.setMaximumSize(QtCore.QSize(16777215, 35))
        self.main_footer.setStyleSheet("background-color: rgb(36, 34, 37);")
        self.main_footer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_footer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_footer.setObjectName("main_footer")
        self.verticalLayout.addWidget(self.main_footer)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.profile_btn.setText(_translate("MainWindow", "Profile"))
        self.time_btn.setText(_translate("MainWindow", "Timer"))
        self.notes_btn.setText(_translate("MainWindow", "Notes"))
        self.settings_btn.setText(_translate("MainWindow", "Settings"))


class SplashScreen(QMainWindow):

    def __init__(self):
        QMainWindow.__init__(self)
        # super().__init__()
        self.ui = Ui_SplashScreen()
        self.ui.setupUi(self)
        self.setWindowFlag(QtCore.Qt.FramelessWindowHint)
        self.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.shadow = QGraphicsDropShadowEffect(self)
        self.shadow.setBlurRadius(20)
        self.shadow.setXOffset(0)
        self.shadow.setYOffset(0)
        self.shadow.setColor(QColor(0, 0, 0, 60))
        self.ui.dropShadowFrame.setGraphicsEffect(self.shadow)
        self.timer = QtCore.QTimer()
        self.timer.timeout.connect(self.progress)
        self.timer.start(35)
        self.ui.label_description.setText("<strong>WELCOME</strong> TO MY APPLICATION")
        QtCore.QTimer.singleShot(1500, lambda: self.ui.label_description.setText("<strong>LOADING</strong> DATABASE"))
        QtCore.QTimer.singleShot(3000, lambda: self.ui.label_description.setText("<strong>LOADING</strong> USER INTERFACE"))
        self.show()

    def progress(self):
        global COUNTER
        self.ui.progressBar.setValue(COUNTER)
        if COUNTER > 100:
            self.timer.stop()
            main = Ui_MainWindow().setupUi(MainWindow)
            main.show()
            self.close()
        COUNTER += 1

import resources_rc

if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    window = SplashScreen()
    sys.exit(app.exec_())
